config/routes.rb
require 'resque/server'

DataVisualizer::Application.routes.draw do
  mount Resque::Server.new, :at => "/resque"
  
  devise_for :users

  resources :projects do
    get :newfileupload
    post :fileupload
    get :ajax_data_load
  end

  root :to => 'projects#index'

end

app/models/project.rb
# Represents the project of an user.
class Project < ActiveRecord::Base
  
  belongs_to :user
  
  has_many :measured_data, dependent: :destroy
  has_many :approximated_measured_data, dependent: :destroy
  has_many :resolutions, dependent: :destroy
  
  attr_accessible :description, :factor, :name, :unit, :comma_separated_resolutions, :line_parse_pattern, :line_element_delimiter, :ignore_first_line
  
  validates :name, :presence => true
  validates :name, :length => { :minimum => 3, :too_short => "Set a name with minimum of 3 chars." }

  validates :unit, :presence => true

  validates :factor, :presence => true
  validates :factor, :numericality => { :only_decimal => true }
  
  validates :comma_separated_resolutions, :presence => true
  validates :comma_separated_resolutions, :format => { :with => /^\s*(\d+(\s*,\s*\d+)*)?\s*$/, :message => "Please write comma delimited integers like '10,60,720,1440'" }
  
  after_create do
    resolution_values = self.comma_separated_resolutions.split(/\s?,\s?/)
    
    # check if the resolution already exists, else create
    self.resolutions = resolution_values.map { |value| self.resolutions.where('value = ?', value).first or self.resolutions.create(:value => value) }
  end
  
  # getter for resolution values
  def comma_separated_resolutions
    if @comma_separated_resolutions
      @comma_separated_resolutions
    elsif self.resolutions.empty?
      '10, 60, 180, 720, 1440, 10080' # default values
    else
      self.resolutions.map { |r| r.value }.join(", ")
    end
  end
  
  # setter for resolution values
  def comma_separated_resolutions=(value)
    @comma_separated_resolutions = value
  end
end

app/controllers/projects_controller.rb
require 'resque'

class ProjectsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = current_user.projects.find(params[:id])

    puts '####################################################'
    puts Resque.size('insert_data_from_csv')
    puts '####################################################'

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = current_user.projects.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  def newfileupload
    @project = current_user.projects.find(params[:project_id])
  end
  
  def fileupload
    @project = current_user.projects.find(params[:project_id])

    @project.line_parse_pattern = params[:line_parse_pattern]
    @project.line_element_delimiter = params[:line_element_delimiter]
    @project.ignore_first_line = params[:ignore_first_line]

    if not @project.save
      # if options are corrupted
      respond_to do |format|
        format.html { redirect_to project_newfileupload_path(@project), alert: 'Options cannot be saved.' }
        format.json { head :no_content }
      end
      return
    end

    file = nil

    # get file object
    begin
      file = params[:datafile].tempfile
    rescue
      # if no file was specified show error and get back to upload form
      respond_to do |format|
        format.html { redirect_to project_newfileupload_path(@project), alert: 'You have to choose a file to upload a file.' }
        format.json { head :no_content }
      end
      return
    end
  
    # add resque job
    #Resque.enqueue(InsertDataFromCSV, @project.id, file)
    MeasuredDatum.insert_data_from_csv(@project.id, file)
    
    respond_to do |format|
      format.html {redirect_to @project, notice: "File upload success. Please wait a few seconds, while all data is processed..."}
    end
  end

  # Load data with ajax request
	def ajax_data_load
		@project = Project.find(params[:project_id])
		
		@data = []
		@data_aggregated = []
		
		# if any data is avaiable
		if not @project.measured_data.empty?
		  
		  # if timespan is given use it to extract data
  		if params.has_key?(:from) and params.has_key?(:to)
  		  from_timestamp, to_timestamp = params[:from], params[:to]
  		  from_time, to_time = Time.at(from_timestamp.to_f/1000), Time.at(to_timestamp.to_f/1000)
  		  
  		# otherwise get all avaiable data
      else 
        from_time = @project.measured_data.minimum(:date)
        to_time = @project.measured_data.maximum(:date)
      end
    
      plot_width = params[:plotwidth].to_i
		
  		interval = to_time - from_time
  		calc_resolution = (interval / 60) / (plot_width / 2)
		
  		# Aufloesung aus gegebenen Aufloesungen waehlen
  		best_resolution = get_best_resolution(calc_resolution, @project.resolutions.map { |r| r.value })
		
		  # time hartcodieren... funktioniert mit sql funktion nicht???
  		db_from = from_time.strftime("%Y-%m-%d %H:%M:%S")
      db_to = to_time.strftime("%Y-%m-%d %H:%M:%S")
    		
  		if best_resolution == 2
  		  cond = "date BETWEEN '#{db_from}' AND '#{db_to}'"
  		  query = @project.measured_data.all(:order => 'date ASC', :conditions => [cond])
  		else
  		  cond = "date BETWEEN '#{db_from}' AND '#{db_to}' AND resolution = #{best_resolution}"
  		  query = @project.approximated_measured_data.all(:order => 'date ASC', :conditions => [cond])
  		end
		
  		query.each do |datum|
        datetime = datum.date.to_time.to_i * 1000
        @data << [datetime, datum.value.to_f]
        @data_aggregated << [datetime, datum.aggregated_value.to_f]
      end
    end 
		respond_to do |format|
		  format.json { render json: [@data, @data_aggregated] }
		end
	end
	
	protected
	
	def get_best_resolution(prop_val, resolutions)
	  resolutions << 2
	  
	  abs_values = {}
	  resolutions.each do |r|
	    abs_values[(prop_val - r).abs] = r
    end
    
    min_key = abs_values.keys.min
    abs_values[min_key]
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form_edit.html.erb
<%= simple_form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :factor, :disabled => true, :hint => 'You cannot change the factor.' %>
  <%= f.input :unit %>
    <%= f.input :comma_separated_resolutions, :disabled => true, :hint => 'Example: "10, 60, 1440" (in minutes)', :label => 'Resolutions' %>
  <%= f.input :description %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/_form_new.html.erb
<%= simple_form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :factor, :disabled => false, :hint => 'You cannot change the factor when it\'s set once.' %>
  <%= f.input :unit %>
  <%= f.input :comma_separated_resolutions, :hint => 'Example: "10, 60, 1440" (in minutes)', :label => 'Resolutions', :default => '10, 60, 1440' %>
  <select id="resolution_chooser">
    <option value="-1" selected="selected">Add a resolution...</option>
    <option value="10">10 minutes</option>
    <option value="60">1 hour</option>
    <option value="180">3 hours</option>
    <option value="720">12 hours</option>
    <option value="1440">1 day</option>
    <option value="10080">1 week</option>
    <option value="43800">1 month</option>
    <option value="131400">3 months</option>
    <option value="262800">6 months</option>
    <option value="525600">1 year</option>
  </select>
  <%= f.input :description %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

<script language="javascript" type="text/javascript">
  $(function() {
    $('#resolution_chooser').change(function() {
      var selValue = $('#resolution_chooser').val();
      
      if (selValue != -1) {
        var currentResolutions = $('#project_comma_separated_resolutions').val();
        
        if (currentResolutions == '') {
          $('#project_comma_separated_resolutions').val(selValue);
        } else {
          $('#project_comma_separated_resolutions').val(currentResolutions + ', ' + selValue);
        }
      }
    });
  });
</script>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form_edit' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:unit) %></th>
      <th><%= model_class.human_attribute_name(:factor) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= project.description %></td>
        <td><%= project.unit %></td>
        <td><%= project.factor %></td>
        <td><%=l project.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form_new' %>

app/views/projects/newfileupload.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Upload a new data file for #{@project.name}" %></h1>
</div>

<%= form_tag({:action => :fileupload}, :multipart => true) do %>
	Upload file: <%= file_field_tag 'datafile' %>
	<br /><br />
	
	<h3>File upload options</h3>
	<div style="float:left">
		Parse pattern for each line:<br />
		<%= text_field_tag 'line_parse_pattern', @project.line_parse_pattern, :style => "width:280px" %><br/>
		<a href="javascript:;" onclick="$('#parse_infos').slideDown('slow');">&raquo; more infos...</a>
		
		<div id="parse_infos" style="display:none;">
			<h5>Possible values</h5>
			<ul style="list-style:none;margin-left:0">
				<li><tt>d(<a href="http://www.ruby-doc.org/stdlib-1.9.3/libdoc/date/rdoc/DateTime.html#method-i-strftime" target="_blank"><i>datetime-format</i></a>)</tt> - datetime element</li> 
				<li><tt>a</tt> - aggregated value</li>
				<li><tt>i</tt> - isolated value</li>
			</ul>
			
			<h5>Conditions</h5>
			<ul style="list-style:disc">
				<li>one or more <tt>d</tt>-values</li>
				<li>least one of the <tt>a</tt>- or <tt>i</tt>-value</li>
			</ul>
			
			<h5>Examples</h5>
			<ul style="list-style:circle">
				<li>d(%Y %m);d(%d);i;d(%T)</li>
				<li>a;i;d(%F)</li>
			</ul>
			
			<a href="javascript:;" onclick="$('#parse_infos').slideUp('slow');">&laquo; hide</a>
		</div>
	</div>
	<div style="float:left;margin-left:20px">
		Line element delimiter:<br />
		<%= text_field_tag 'line_element_delimiter', @project.line_element_delimiter, :size => 1, :max_length => 1, :style => "width:30px" %>
		<br />
		Ignore first line of file?<br />
		<%= check_box_tag 'ignore_first_line', true, @project.ignore_first_line %>
	</div>
	
	<div class="form-actions" style="clear:both;">
	  <%= link_to t('.back', :default => t("helpers.links.back")),
	              project_path(@project), :class => 'btn'  %>
	  <%= submit_tag 'Upload', :class => 'btn btn-primary' %>
	</div>
<% end %>

app/views/projects/show.html.erb
<% if Resque.info[:failed].to_i > 0 %>
<!--<div class="alert alert-error">
  <a class="close" data-dismiss="alert">&#215;</a>
  <%= content_tag :div, "Import jobs failed: #{Resque.info[:failed]}" %>
</div>-->
<% end %>

<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => "#{model_class.model_name.human}: #{@project.name}" %></h1>
  <div style="color: #a0a0a0;margin-top:10px">
    <%= model_class.human_attribute_name(:factor) %>: <strong><%= @project.factor %></strong>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<%= model_class.human_attribute_name(:unit) %>: <strong><%= @project.unit %></strong>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<%= model_class.human_attribute_name(:resolutions) %>: <strong><%= @project.comma_separated_resolutions %></strong>
    <br />
    <%= @project.description %>
  </div>
</div>

<div id="container" style="min-width: 400px; height: 500px; margin: 0 auto"></div>

<div id="nodata" class="alert alert-error" style="display:none">
  <%= content_tag :div, "No Data yet!" %>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
  <%= link_to t('.upload_new_file', :default => t("helpers.links.upload_new_file")),
              project_newfileupload_path(@project),
              :class => 'btn btn-primary' %>
</div>

<script type="text/javascript">

function onSetExtremes(e) { 
	currentExtremes = e.target.getExtremes();
	if (e.min !== currentExtremes.min || e.max !== currentExtremes.max) {
		loadData(e.min, e.max);
	}
}

function loadData(from_timestamp, to_timestamp) {
	//console.log(from_timestamp);
	//console.log(to_timestamp);	
	// Parameter vorhanden?
  params = '?plotwidth=' + window.chart.plotWidth;
  if (from_timestamp != undefined && to_timestamp != undefined) {
    params += '&from=' + from_timestamp + '&to=' + to_timestamp;
  }
  
  window.chart.showLoading('Loading data...');

  // Ajax-Anfrage nach Graphdaten in passender Aufloesung
  $.getJSON('<%= project_ajax_data_load_path(@project) %>.json' + params, function(data) {        
    if (data[0].length) {
      xData = window.chart.series[0].xData;
      xDataAggregated = window.chart.series[1].xData;
      
      // Vorhandene Daten und neu geladene Daten zusammenfuehren
      if (xData.length != 0 && xDataAggregated.length != 0) {
        firstIndex = -1;
        lastIndex = -1;
      
        for (var i = 0; i < xData.length; i++) {
          if (xData[i] >= data[0][0][0] && firstIndex == -1) {
            firstIndex = i;
          }
          if (xData[i] >= data[0][data[0].length-1][0] && lastIndex == -1) {
            lastIndex = i;
          }
        }

        chartData = window.chart.series[0].options.data;
        dataLength = chartData.length;      
        lastArray = chartData.slice(lastIndex, dataLength - 1);
        firstArray = chartData.slice(0, firstIndex);
        newData = $.merge($.merge(firstArray, data[0]), lastArray)
        
        for (var i = 0; i < xDataAggregated.length; i++) {
          if (xDataAggregated[i] >= data[1][0][0] && firstIndex == -1) {
            firstIndex = i;
          }
          if (xDataAggregated[i] >= data[1][data[1].length-1][0] && lastIndex == -1) {
            lastIndex = i;
          }
        }
        
        chartDataAggregated = window.chart.series[1].options.data;
        dataLength = chartDataAggregated.length;      
        lastArray = chartDataAggregated.slice(lastIndex, dataLength - 1);
        firstArray = chartDataAggregated.slice(0, firstIndex);
        newDataAggregated = $.merge($.merge(firstArray, data[1]), lastArray)
        
        window.chart.series[0].setData(newData, true);
        window.chart.series[1].setData(newDataAggregated, true);
      } else {
        window.chart.series[0].setData(data[0], true);
        window.chart.series[1].setData(data[1], true);
      }
    } else {
      $('#container').hide();
      $('#nodata').show();
    }
    //window.chart.options = { subtitle : { text : data.length + " data elements has been loaded" } };
    window.chart.hideLoading();
  });
}

$(function() {

	// Create the chart
	window.chart = new Highcharts.StockChart({
		chart : {
			renderTo : 'container',
			zoomType: 'x'
		},
		
		credits : {
		  enabled : false
		},

		rangeSelector : {
			selected : 4,
			buttons: [
			{
				type: 'hour',
				count: 1,
				text: '1h'
			},
			{
				type: 'day',
				count: 1,
				text: '1d'
			},
			{
				type: 'month',
				count: 1,
				text: '1m'
			}, 
			{
				type: 'year',
				count: 1,
				text: '1y'
			},
			{
				type: 'all',
				text: 'All'
			}]
		},

		title : {
			text : '<%= @project.name %>'
		},
		
	  xAxis : {
		  events : {
			  setExtremes : onSetExtremes
		  },
		  ordinal: false
    },
		
		point : {
		  color : '#C80000'
		},
		
		yAxis : [{
		  title :  {
		    text : 'Current <%= @project.unit %>'
		  },
		},
		{
		  title :  {
		    text : 'Total <%= @project.unit %>',
		    style: {
        	color: '#C80000'
        }
		  },
		  labels : {
		    style: {
        	color: '#C80000'
        }
		  },
		  opposite: true
		}],
		
		series : [{
			name : 'Current',
			type : 'area',
			dataGrouping : {
				enabled : false
			},
			tooltip : {
				valueDecimals : 2,
				valueSuffix : ' <%= @project.unit %>'
			},
			yAxis: 0,
			cropThreshold: 0,
			fillColor : {
				linearGradient : {
					x1: 0, 
					y1: 0, 
					x2: 0, 
					y2: 1
				},
				stops : [[0, Highcharts.getOptions().colors[0]], [1, 'rgba(0,0,0,0)']]
			}
		},
		{
			name : 'Total',
			type : 'line',
			dataGrouping : {
				enabled : false
			},
    	color: '#C80000',
			tooltip : {
				valueDecimals : 2,
				valueSuffix : ' <%= @project.unit %>'
			},
			yAxis: 1,
			cropThreshold: 0
		}]
	});

  loadData();
  
  $(".highcharts-range-selector").datepicker();
  $(".highcharts-range-selector").datepicker("option", "dateFormat", "yy-mm-dd");
});

</script>