config/routes.rb
require 'resque/server'

DataVisualizer::Application.routes.draw do
  mount Resque::Server.new, :at => "/resque"
  
  devise_for :users

  resources :projects do
    get :newfileupload
    post :fileupload
    get :ajax_data_load
  end

  root :to => 'projects#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DataVisualizer" %></title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/apple-touch-icon-144x144-precomposed.png">
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/apple-touch-icon-114x114-precomposed.png">
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/apple-touch-icon-72x72-precomposed.png">
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <link rel="apple-touch-icon-precomposed" href="images/apple-touch-icon-precomposed.png">
    <!-- Size should be 32 x 32 pixels -->
    <link href="images/favicon.ico" rel="shortcut icon">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">DataVisualizer</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Projects", projects_url %></li>
            </ul>
			<div style="float:right;">
			  <% if user_signed_in? %>
			    Signed in as <%= current_user.email %>.
			    <%= link_to t('.destroy', :default => t("helpers.links.sign_out")),
		                      destroy_user_session_path,
		                      :method => :delete,
		                      :class => 'btn btn-mini btn-danger' %>
			  <% else %>
				<%= link_to t('.sign_in', :default => t("helpers.links.sign_in")),
		                      new_user_session_path,
		                      :class => 'btn btn-mini' %>
				<%= link_to t('.sign_up', :default => t("helpers.links.sign_up")),
		                      new_user_registration_path,
		                      :class => 'btn btn-primary btn-mini' %>
			  <% end %>
			</div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
		<div class="row">
		  <div class="span12">
		    <% flash.each do |name, msg| %>
		      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
		        <a class="close" data-dismiss="alert">&#215;</a>
		        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		      </div>
		    <% end %>
		  </div>
	    </div>
        <div class="row">
           <div class="span12">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    

  </body>
</html>